server:
  port: ${PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false

  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always

iex:
  base:
    url: ${IEX_BASE_URL}
  token: ${IEX_TOKEN}